services:
  web:
    image: nginx:stable-alpine
    volumes:
     - .:/usr/share/nginx/html
    ports:
     - "82:80"
    environment:
     - NGINX_HOST=185.246.155.142
     - NGINX_PORT=80
